### ISSUE TITLE
Differences between adlik and other similar types

### ISSUE THREAD

**Issue by elsa623** [Adlik/Adlik#110]
Adlik does compression optimization for the model, but ONNX Runtime, Baidu's PaddleSlim and others all have similar functions, so what's the difference between them?

**Comment by ChengcanWang-com** [comment]
Adlik model optimization, focusing on and running on specific hardware to achieve the purpose of acceleration. Because sparsity pruning depends on special algorithms and hardware to achieve acceleration, the usage scenarios are limited. Adlik pruning focuses on channel pruning and filter pruning, which can really reduce the number of parameters and flops. In terms of quantization, Adlik focuses on 8bit quantization because it is easier to accelerate on specific hardware. After testing, it is found that running a small batch of data sets can obtain a quantitative model with little loss of accuracy, so Adlik focuses on this method.

**Comment by amadeus-zte** [comment]
@elsa623 Do you have any other question on model optimizer?

**Comment by shiyingjin** [comment]
Please open a new issue if you have further questions.
